export const REQUEST_QUESTIONS_PENDING = 'REQUEST_QUESTIONS_PENDING';
export const REQUEST_QUESTIONS_SUCCESS = 'REQUEST_QUESTIONS_SUCCESS';
export const REQUEST_QUESTIONS_FAILED = 'REQUEST_QUESTIONS_FAILED';
export const RETURN_QUESTION = 'RETURN_QUESTION';

export const QUESTION_INDEX_ADD = 'QUESTION_INDEX_ADD';
export const QUESTION_INDEX_MIN = 'QUESTION_INDEX_MIN';

export const SAVE_QUESTIONS_ANSWERS = 'SAVE_QUESTIONS_ANSWERS';