export const RETURN_QUESTION = 'RETURN_QUESTION';

export const QUESTION_INDEX_ADD = 'QUESTION_INDEX_ADD';
export const QUESTION_INDEX_MIN = 'QUESTION_INDEX_MIN';

export const SAVE_QUESTIONS_ANSWERS = 'SAVE_QUESTIONS_ANSWERS';