export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_QUESTIONS_PENDING = 'REQUEST_QUESTIONS_PENDING';
export const REQUEST_QUESTIONS_SUCCESS = 'REQUEST_QUESTIONS_SUCCESS';
export const REQUEST_QUESTIONS_FAILED = 'REQUEST_QUESTIONS_FAILED';